---
title: "Murundus: hotspots of biodiversity, nutrient enrichment, and gas fluxes through termite activity"
description: |
  .....
categories:
  - Poster Presentation
#  - 2022
date: 01-06-2023
preview: conceptual_model9.png
output:
  distill::distill_article:
    self_contained: true

---
**authors:** *Yuri Souza & Amy Zanne*


## **Abstract**
Campos de Murundus, or earthmounds, are discrete mounds surrounded by grass common throughout the Brazilian Savanna. Such sites favor colonization by plants and by termites¹, which play a significant role in ecosystem dynamics and maintenance through organic matter decomposition and gas fluxes. I aim to address how Campos de murundus drives ecosystem dynamics in a spatial gradient. For this, we will perform a literature review and data collection in the Brazilian Savanna Cerrado. We hypothesize the existence of a gradient of termite diversity, soil nutrient enrichment, plant functional composition, and gas fluxes increasing from an open grass field of the Savanna to the Murundus.


Unfortunately, our poster size is too heavy, so it was impossible to load it on this webpage. Please click [here](https://github.com/souzayuri/betterposter_um_grad_symp_2023/blob/main/Yuri_Souza_PSI_poster.pdf) to access it from my GitHub and check the details of our research.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<!-- adding share buttons on the right side of the page -->
<!-- AddToAny BEGIN -->
<div class="a2a_kit a2a_kit_size_32 a2a_floating_style a2a_vertical_style" style="right:0px; top:150px; data-a2a-url="https://souzayuri.github.io/" data-a2a-title="Yuri Souza">
<a class="a2a_button_twitter"></a>
</div>
<script>
var a2a_config = a2a_config || {};
a2a_config.onclick = 1;
</script>
<script async src="https://static.addtoany.com/menu/page.js"></script>
<!-- AddToAny END -->
